### ISSUE TITLE
Icon Theme section query should be case insensitive

### ISSUE THREAD

**Issue by kchibisov** [esposm03/xcursor-rs#1]
For example such `index.theme` is failing.

```
[icon theme]
Inherits=Adwaita
```

The `Inherits`, etc are case sensitive, however section name is not.

**Comment by esposm03** [comment]
@kchibisov The spec says that files are case-sensitive, as the index.theme format is a cut-down version of the .desktop file format (see the [icon theme spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#file_formats))

The [desktop entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s03.html) specifies that
> Case is significant everywhere in the file.

Is your index.theme parsed correctly by other implementations?

**Comment by kchibisov** [comment]
Yeah, libwayland-cursor, etc, are parsing it as a valid thing.

**Comment by esposm03** [comment]
Okay, will correct that then.

**Comment by kchibisov** [comment]
I feel like `libwayland-cursor` doesn't even check section name, and just checks for `Inherits`, since 

```
Inherits=Adwaita
```

is also works just fine for it https://gitlab.freedesktop.org/wayland/wayland/-/blob/master/cursor/xcursor.c#L763. I'm not sure that's the right thing to do so.

**Comment by esposm03** [comment]
@kchibisov Fixed, and published a new version!

**Comment by vberger** [comment]
Just wanted to note this nice side-effect: :smiley: 

```
    Updating crates.io index
    Removing ahash v0.3.3
      Adding aho-corasick v0.7.10
    Removing dlv-list v0.2.2
    Removing getrandom v0.1.14
    Removing hashbrown v0.7.2
      Adding memchr v2.3.3
    Removing ordered-multimap v0.2.4
    Removing ppv-lite86 v0.2.6
    Removing rand v0.7.3
    Removing rand_chacha v0.2.2
    Removing rand_core v0.5.1
    Removing rand_hc v0.2.0
      Adding regex v1.3.7
      Adding regex-syntax v0.6.17
    Removing rust-ini v0.15.2
      Adding thread_local v1.0.1
    Removing wasi v0.9.0+wasi-snapshot-preview1
    Updating xcursor v0.1.1 -> v0.1.2
```
