### ISSUE TITLE
Ignores file offset of TOC / assumes that file is sanely laid out

### ISSUE THREAD

**Issue by psychon** [esposm03/xcursor-rs#17]
Hi there,

as things go, [I have my own implementation of the Xcursor file format and was asked whether it would not be better to switch to your crate](https://github.com/psychon/x11rb/issues/934). Thus, I am comparing what we do.

Let's look at the first things in a cursor file. The first four entries are called `magic`, `header`, `version` and `ntoc` in my code. https://github.com/psychon/x11rb/blob/3e6b5eaae30d3c9e58235799c9a5b3e1d1d7e5a8/x11rb/src/cursor/parse_cursor.rs#L153

- `magic` must be an exact value. Same in xcursor-rs (I like your version of this better than mine; I have a magic number and you have `Xcur`, which is way more intuitive
- `header` is an offset in bytes from the beginning of the file where the table of contents starts: https://github.com/psychon/x11rb/blob/3e6b5eaae30d3c9e58235799c9a5b3e1d1d7e5a8/x11rb/src/cursor/parse_cursor.rs#L168-L172 but your code just ignores this field: https://github.com/esposm03/xcursor-rs/blob/b57f683c7ec48bfe14ad85850d32b0da0804025b/src/parser.rs#L60
- The `version` field we both ignore
- For the `ntoc` field, I have a limit of 65k, while your code has no limit: https://github.com/psychon/x11rb/blob/3e6b5eaae30d3c9e58235799c9a5b3e1d1d7e5a8/x11rb/src/cursor/parse_cursor.rs#L164-L166

I don't know if any of these differences are really important. I can live with no limit on the number of entries, because why would anyone load a "malicious" cursor file.

I am not so sure about ignoring the `header` field / offset of the TOC and want to leave it to you what to do about it. If you want, I can try to come up with a PR that changes this.

(For the individual images, your code does use the file offset: https://github.com/esposm03/xcursor-rs/blob/b57f683c7ec48bfe14ad85850d32b0da0804025b/src/parser.rs#L144-L145)

Another thing I noticed: My code has a limit on the width and height of the image of 32k: https://github.com/psychon/x11rb/blob/3e6b5eaae30d3c9e58235799c9a5b3e1d1d7e5a8/x11rb/src/cursor/parse_cursor.rs#L74-L84
This ensures that `width * height` cannot overflow. Your crate just parses the fields and does the multiplication without worrying about overflow: https://github.com/esposm03/xcursor-rs/blob/b57f683c7ec48bfe14ad85850d32b0da0804025b/src/parser.rs#L93
I'll open a PR about this in a moment.

**Comment by psychon** [comment]
Ah, I figured out again where that maximum cursor size comes from: libXcursor: https://gitlab.freedesktop.org/xorg/lib/libxcursor/-/blob/09617bcc9a0f1b5072212da5f8fede92ab85d157/src/file.c#L457

This checks that each of width and height is at most `XCURSOR_IMAGE_MAX_SIZE`, which is defined in the public header: https://gitlab.freedesktop.org/xorg/lib/libxcursor/-/blob/09617bcc9a0f1b5072212da5f8fede92ab85d157/include/X11/Xcursor/Xcursor.h.in#L180

If you like, I can do a PR that adds a similar restriction to this library.

(Sorry for mixing two things into one issue)

**Comment by esposm03** [comment]
I have just implemented both things in commit 0859d4. Will do more testing and then release a new version

**Comment by esposm03** [comment]
Alright, I've just published this (and the other changes you requested/contributed) in version 0.3.7 @psychon
