### ISSUE TITLE
Does not use Xcursor.theme from resource database as fallback

### ISSUE THREAD

**Issue by psychon** [esposm03/xcursor-rs#24]
Hi there,

I just got a PR about the cursor implementation in x11rb: https://github.com/psychon/x11rb/pull/936

Due to that, I looked at what libXcursor is doing and found a difference to your crate. [libXcursor falls back to using `Xcursor.theme` from the X11 resource database if `$XCURSOR_THEME` is not set](https://gitlab.freedesktop.org/xorg/lib/libxcursor/-/blob/09617bcc9a0f1b5072212da5f8fede92ab85d157/src/display.c#L216-218). xcursor-rs instead [seems to fall back to XDG data directory](https://github.com/esposm03/xcursor-rs/blob/68c3555283dfd59f973cba13a4916f1f34aac76f/src/lib.rs#L150-L152) if the env var is missing.

No idea what to do about this. Your crate does not have an X11 connection and does not have access to the X11 resource database. So, the only idea that would come to my mind would be turn this into the caller's problem: Add a new function that needs to pass in e.g. an `Option<&str>` containing the value of `Xcursor.theme`.

(x11rb also does not implement this fallback and neither does libxcb-cursor, which was used as the inspiration for x11rb's implementation)

**Comment by esposm03** [comment]
I'm actually not too familiar with that X11 resource, but isn't that just a way to specify a cursor theme _name_, not to override where it is searched for? If you look at the libXcursor source, it looks for that resource if the variable `XCURSOR_THEME` is not specified, while the only envvar this crate reads is `XCURSOR_PATH`.

I think you should just be able to call `CursorTheme::load` with the appropriate name, and on your side implement the logic to read the Xresource, if necessary.

**Comment by psychon** [comment]
> I'm actually not too familiar with that X11 resource,

No worries. No one is. :-)

> a way to specify a cursor theme name, not to override where it is searched for

Whoops. Sorry for the noise. Apparently I cannot read. :see_no_evil: 

You are right that I mixed something up here. Figuring out the name of the active cursor theme is not part of this crate anyway.
